newsportal/news/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeNewsView.as_view(), name='home'),
    path('category/<int:category_id>/', views.NewsByCategory.as_view(), name='category'),
    path('news/<int:news_id>/', views.PostDetailView.as_view(), name='view_news'),
    path('news/add-news/', views.CreateNews.as_view(), name='add_news'),
    path('news/articles/', views.ArticleView.as_view(), name='articles'),
    path('news/news/', views.NewsView.as_view(), name='news'),
    path('news/update/<int:pk>/', views.UpdateNews.as_view(), name='update_news'),
    path('news/delete/<int:pk>/', views.DeleteNews.as_view(), name='delete_news'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
]

newsportal/newsportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
]

newsportal/news/models.py
from django.db import models
from django.db.models import Sum
from django.urls import reverse

from django.utils import timezone

from django.contrib.auth.models import User


class Author(models.Model):
    author_user = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.SmallIntegerField(default=0)

    def update_rating(self):
        post_rat = self.post_set.aggregate(postRating=Sum('rating'))
        p_rat = 0
        p_rat += post_rat.get('postRating')

        comment_rat = self.author_user.comment_set.aggregate(commentRating=Sum('rating'))
        c_rat = 0
        c_rat += comment_rat.get('commentRating')

        self.author_rating = p_rat * 3 + c_rat
        self.save()

    def __str__(self):
        return self.author_user.username


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_id': self.pk})

    def __str__(self):
        return self.name.title()


class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    type_category = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    rating = models.SmallIntegerField(default=0)

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('view_news', kwargs={'news_id': self.pk})

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.content[0:123] + '...'


# class PostCategory(models.Model):
#     post_through = models.ForeignKey(Post, on_delete=models.CASCADE)
#     category_through = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_creation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='subscriptions')
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, related_name='subscriptions')

    def __str__(self):
        return self.category.name

newsportal/templates/inc/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Новостной сайт</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Главная</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'articles' %}">Статьи</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'news' %}">Новости</a></li>

            {% if perms.news.add_post %}
            <li class="nav-item"><a class="nav-link" href="{% url 'add_news' %}">Добавить новость</a></li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'subscriptions' %}">Подписка</a></li>
            {% endif %}

        </ul>

        <span class="navbar-text">

            {% if request.user.is_authenticated %}
            Welcome, {{ user.username }} | <a href="{% url 'logout' %}">Выход</a>
            {% else %}
            <a href="{% url 'register' %}">Register</a> | <a href="{% url 'login' %}">Login</a>
            {% endif %}

        </span>
    </div>
</nav>

newsportal/templates/inc/_sidebar.html
{% load news_tags %}

{% comment %}
{% get_categories as categories %}
<div class="list-group">
    {% for item in categories %}
    <a href="{% url 'category' item.pk %}" class="list-group-item list-group-item-action">{{ item.name }}</a>
    {% endfor %}
</div>
{% endcomment %}

{% show_categories %}

newsportal/templates/inc/pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="...">
    <ul class="pagination">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
        </li>
        {% endif %}

        {% for p in page_obj.paginator.page_range %}

        {% if page_obj.number == p %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ p }}">{{ p }} <span class="sr-only">(current)</span></a>
        </li>
        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}